### ISSUE TITLE
`Command` <- Export | Command with flags and without failed to execute with an exception

### ISSUE THREAD

**Issue by XFaonAE** [AxeriDev/Ember#3]
```
PS C:\users\xfaon\Documents\VisualStudioCode\EmberCli> ember --config=test/ember.config.js
C:\Users\xfaon\Documents\VisualStudioCode\EmberCli\node_modules\@axeridev\ember\src\command\Command.js:144
            this.checkFlagErrors(flags, command.options.flags).then((invalidFlags) => {
                                                ^

TypeError: Cannot read property 'options' of undefined
    at C:\Users\xfaon\Documents\VisualStudioCode\EmberCli\node_modules\@axeridev\ember\src\command\Command.js:144:49
PS C:\users\xfaon\Documents\VisualStudioCode\EmberCli> ember --config=test/ember.config.js
C:\Users\xfaon\Documents\VisualStudioCode\EmberCli\node_modules\@axeridev\ember\src\command\Command.js:144
            this.checkFlagErrors(flags, command.options.flags).then((invalidFlags) => {
                                                ^

TypeError: Cannot read property 'options' of undefined
    at C:\Users\xfaon\Documents\VisualStudioCode\EmberCli\node_modules\@axeridev\ember\src\command\Command.js:144:49
PS C:\users\xfaon\Documents\VisualStudioCode\EmberCli> ember --config=test/ember.config.js
C:\Users\xfaon\Documents\VisualStudioCode\EmberCli\node_modules\@axeridev\ember\src\command\Command.js:144
            this.checkFlagErrors(flags, command.options.flags).then((invalidFlags) => {
                                                ^

TypeError: Cannot read property 'options' of undefined
    at C:\Users\xfaon\Documents\VisualStudioCode\EmberCli\node_modules\@axeridev\ember\src\command\Command.js:144:49
```

**Comment by XFaonAE** [comment]
Reason: command object is undefined for no apparent cause

**Comment by XFaonAE** [comment]
Reason Found! When a command is triggered without a real trigger and just a flag, command with look for commands with the flag
Solutions: Use trigger: `""` if arg1 starst with -- or -

**Comment by XFaonAE** [comment]
Version: v0.0.7
